name: Destroy Resources
on:
  workflow_dispatch:  # This allows manual triggering of the workflow
jobs:
  destroy_resources:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your desired region
    - name: Destroy EC2 Instance
      run: |
        INSTANCE_ID="your-instance-id"  # Replace with the instance ID you want to terminate
        aws ec2 terminate-instances --instance-ids $INSTANCE_ID
        echo "EC2 Instance terminated: $INSTANCE_ID"